apiVersion: apps/v1
kind: Deployment
metadata:
     name: bridge-deploy
spec:
     strategy:
          type: RollingUpdate
     replicas: 3
     selector:
          matchLabels:
               version: bridge-latest
     template:
          # pod manifest file from metadata till the container definition
          metadata:
               name: bridge-pod
               labels:
                    version: bridge-latest
          spec:
               containers:
                    - name: bridge-container
                      image: kubearyan/bridge:latest
                      ports: 
                           - containerPort: 3000
                           - containerPort: 8080
                           - containerPort: 8900
---

apiVersion: v1
kind: Service
metadata:
    name: bridge-node-port
    labels:
          run: node-port
spec:
    type: NodePort
    selector:
          version: bridge-latest 
    ports:
          - port: 3000
            targetPort: 3000
            nodePort: 30000
